workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and get packages
        script: |
          flutter clean
          flutter pub get
      - name: Disable Swift Package Manager
        script: |
          flutter config --no-enable-swift-package-manager
      - name: Pod install
        script: |
          cd ios
          pod deintegrate || true
          pod cache clean --all
          pod install --repo-update
      - name: Build iOS (unsigned)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
